# straight forward
icons: true

# keeps going after a successful login
loop: true

# gnupg public key id used for encrypting/decrypting passwords
# set it to 'plain' for saving passwords in plain text (not recommended
# but still)
# if not set, the program will prompt your for a key or plain
gpg: plain

# displays the percentage in the bottom right
percent: false

# if set, will open your command in the specified terminal emulator. works great
# with loop set to true. will handle the env variable $TERMINAL if set as such
# if commented or unset,
# the command will replace hardflip
#terminal: alacritty

# this will be entered by default when adding a new SSH or SSH jump host to win
# some time
default_ssh_priv: path/to/key

# fuzzy finder program used in search (keybind /) and -s mode
#fuzzy_finder: fzf
